version: '3.4'

networks:
  dev:
    driver: bridge
services:
  egma.api:
    image: ${DOCKER_REGISTRY-}egmaapi
    depends_on:
     - "egma.database"
    build:
      context: .
      dockerfile: egma.API/Dockerfile
    ports:
      - "7261:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTPS_PORTS=7261
      - ASPNETCORE_URLS=https://+:443
    volumes:
      - D:\egma:/app/Files:rw
    networks:
      - dev
  egma.database:
    image: postgres:latest
    container_name: egma.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=egmaContext
    ports:
      - "5433:5432"
    volumes:
      - ./.containers/egma_db:/var/lib/postgresql/data
    networks:
      - dev